name: schedule

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  tuan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - name: Run script
        run: npm run tuan
        env:
          SELF_EMAIL: ${{ secrets.SELF_EMAIL }}
          SELF_EMAIL_TOKEN: ${{ secrets.SELF_EMAIL_TOKEN }}
          TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
          MID: ${{ secrets.MID }}
